// Writes the preset-theme seed migration from lib/themes.ts (single source of truth).
import { writeFileSync } from "node:fs";
import { PRESET_THEMES } from "../lib/themes";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const arr = (a: string[]) => `array[${a.map(q).join(", ")}]::text[]`;

const rows = PRESET_THEMES.map(
  (t) => `  (null, ${q(t.slug)}, ${q(t.name)}, ${q(t.description)}, ${arr(t.palette)}, ${arr(t.materials)}, ${arr(t.mood)}, true)`,
).join(",\n");

writeFileSync(
  "supabase/migrations/20261002000003_preset_themes.sql",
  `-- Generated by scripts/gen-theme-migration.ts. Do not edit by hand.
insert into public.themes (owner_id, slug, name, description, palette, materials, mood, is_preset) values
${rows}
on conflict (slug) where owner_id is null do update set
  name = excluded.name, description = excluded.description, palette = excluded.palette,
  materials = excluded.materials, mood = excluded.mood;
`,
);
