// Bakes the "Virtually staged (AI-generated)" label into a PNG so runtime watermarking
// needs no fonts (serverless hosts often have none). Run: npx tsx scripts/make-watermark.ts
import { writeFileSync } from "node:fs";
import sharp from "sharp";

const W = 760;
const H = 104;
const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}">
  <rect x="0" y="0" width="${W}" height="${H}" rx="52" fill="#000" fill-opacity="0.62"/>
  <g transform="translate(44 52)" fill="none" stroke="#fff" stroke-width="5" stroke-linejoin="round">
    <path d="M0 -26 L6 -6 L26 0 L6 6 L0 26 L-6 6 L-26 0 L-6 -6 Z" fill="#fff"/>
  </g>
  <text x="92" y="67" font-family="Segoe UI, Helvetica, Arial, sans-serif" font-size="44" font-weight="600" fill="#fff">Virtually staged (AI-generated)</text>
</svg>`;

sharp(Buffer.from(svg))
  .png()
  .toBuffer()
  .then((buf) => {
    writeFileSync("lib/images/assets/watermark.png", buf);
    writeFileSync(
      "lib/images/assets/watermark.ts",
      `// Generated by scripts/make-watermark.ts. Do not edit.
export const WATERMARK_PNG_BASE64 =
  "${buf.toString("base64")}";
export const WATERMARK_ASPECT = ${W / H};
`,
    );
  });
